### ISSUE TITLE
The release package contains unnecessary metadata

### ISSUE THREAD

**Issue by nicolas-lang** [shakiata/fluxcap_0.0.1#1]
The released package contains unnecessary metadata:
![image](https://user-images.githubusercontent.com/635895/130487489-ebf837fd-7541-424d-bea4-fa007acf2402.png)
![image](https://user-images.githubusercontent.com/635895/130488006-95bf7f98-5bd9-409c-b781-58cd8345e83c.png)

I would suggest:
- a cleanup of repository ( add gitignore file and include .DS_STORE to gitignore ) 
- removal of the .git and __MACOSX folders from released zip

**Comment by AmyTazenda** [comment]
This appears to have been taken care of by @shakiata, thanks for the assist :)
